import{a as v,S,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="53405019-6c96446ba48ce1565d886076e",E="https://pixabay.com/api/";async function g(e,r=1){const s={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await v.get(E,{params:s})).data}catch(n){throw n}}const P=new S(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function m(e){const r=document.querySelector(".gallery"),s=e.map(({webformatURL:n,largeImageURL:t,tags:o,likes:a,views:b,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a href="${t}">
            <img src="${n}" alt="${o}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes:</strong> ${a}</p>
            <p><strong>Views:</strong> ${b}</p>
            <p><strong>Comments:</strong> ${L}</p>
            <p><strong>Downloads:</strong> ${w}</p>
          </div>
        </li>
      `).join("");r.insertAdjacentHTML("beforeend",s),P.refresh()}function I(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){document.querySelector("#loader").classList.add("is-visible")}function y(){document.querySelector("#loader").classList.remove("is-visible")}function M(){document.querySelector(".load-more-button").classList.add("is-visible")}function d(){document.querySelector(".load-more-button").classList.remove("is-visible")}const l="Sorry, there are no images matching your search query. Please try again!",p="We're sorry, but you've reached the end of search results.",B=document.querySelector("#search-form"),O=document.querySelector(".load-more-button");d();let h="",i=1,u=0;B.addEventListener("submit",async e=>{e.preventDefault();const r=e.currentTarget.searchQuery.value.trim();if(!r){c.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}h=r,i=1,u=0,I(),f();try{const s=await g(r,i);if(s.hits.length===0)throw new Error(l);u=s.totalHits,m(s.hits),i*15<u?M():(d(),c.info({title:"Info",message:p,position:"topRight"}))}catch(s){c.error({title:"Error",message:s.message||l,position:"topRight"})}finally{y()}});O.addEventListener("click",async()=>{i+=1,f();try{const e=await g(h,i);if(e.hits.length===0)throw new Error(l);m(e.hits),i*15>=e.totalHits&&(d(),c.info({title:"Info",message:p,position:"topRight"})),R()}catch(e){c.error({title:"Error",message:e.message||l,position:"topRight"}),i-=1}finally{y()}});function R(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const n=e[0].getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
