import{a as v,S,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const q="53405019-6c96446ba48ce1565d886076e",E="https://pixabay.com/api/";async function m(e,o=1){const s={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await v.get(E,{params:s})).data}catch(n){throw n}}const P=new S(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function g(e){const o=document.querySelector(".gallery"),s=e.map(({webformatURL:n,largeImageURL:t,tags:r,likes:a,views:b,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a href="${t}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes:</strong> ${a}</p>
            <p><strong>Views:</strong> ${b}</p>
            <p><strong>Comments:</strong> ${L}</p>
            <p><strong>Downloads:</strong> ${w}</p>
          </div>
        </li>
      `).join("");o.insertAdjacentHTML("beforeend",s),P.refresh()}function M(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){document.querySelector("#loader").classList.add("is-visible")}function y(){document.querySelector("#loader").classList.remove("is-visible")}function B(){document.querySelector(".load-more-button").classList.add("is-visible")}function p(){document.querySelector(".load-more-button").classList.remove("is-visible")}const l="Sorry, there are no images matching your search query. Please try again!",I="We're sorry, but you've reached the end of search results.",O=document.querySelector("#search-form"),d=document.querySelector(".load-more-button");d.disabled=!0;let h="",i=1,u=0;O.addEventListener("submit",async e=>{e.preventDefault();const o=e.currentTarget.searchQuery.value.trim();if(!o){c.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}h=o,d.disabled=!1,i=1,u=0,M(),p(),f();try{const s=await m(o,i);if(s.hits.length===0)throw new Error(l);u=s.totalHits,g(s.hits),i*15<u&&B()}catch(s){c.error({title:"Error",message:s.message||l,position:"topRight"})}finally{y()}});d.addEventListener("click",async()=>{i+=1,f();try{const e=await m(h,i);if(e.hits.length===0)throw new Error(l);g(e.hits),i*15>=e.totalHits&&(p(),c.info({title:"Info",message:I,position:"topRight"})),$()}catch(e){c.error({title:"Error",message:e.message||l,position:"topRight"}),i-=1}finally{y()}});function $(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const n=e[0].getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
